export const regionIds = [
  'danube-plain',
  'black-sea',
  'rose-valley',
  'thracian-lowland',
  'struma-valley',
] as const

export type RegionId = (typeof regionIds)[number]

export type WineStyle =
  | 'Red'
  | 'White'
  | 'Rosé'
  | 'Sparkling'
  | 'Orange / low-intervention'
  | 'Dessert'

export type Experience =
  | 'Tastings'
  | 'Cellar tour'
  | 'Stay'
  | 'Restaurant'
  | 'Events'
  | 'Family-friendly'

export interface Region {
  id: RegionId
  name: string
  shortName: string
  color: string
  pale: string
  description: string
  climate: string
  signatures: string[]
  mapLabel: { lon: number; lat: number }
}

export interface Winery {
  id: string
  name: string
  nameBg?: string
  locality: string
  province: string
  region: RegionId
  lat: number
  lon: number
  summary: string
  styles: WineStyle[]
  grapes: string[]
  experiences: Experience[]
  featured?: boolean
  organic?: boolean
  website?: string
}

export const regions: Region[] = [
  {
    id: 'danube-plain',
    name: 'Danube Plain',
    shortName: 'Danube',
    color: '#9a7a3c',
    pale: '#eee3c6',
    description: 'Broad northern plateaus, river light and long continental seasons give this region a quietly confident range.',
    climate: 'Continental · warm summers, cold winters',
    signatures: ['Gamza', 'Vrachanski Misket', 'Cabernet Sauvignon'],
    mapLabel: { lon: 24.65, lat: 43.66 },
  },
  {
    id: 'black-sea',
    name: 'Black Sea Coast',
    shortName: 'Black Sea',
    color: '#397b78',
    pale: '#d8e8e4',
    description: 'Sea breezes and a gentler autumn favour bright, aromatic whites along Bulgaria’s eastern edge.',
    climate: 'Maritime influence · mild, breezy autumns',
    signatures: ['Dimyat', 'Red Misket', 'Riesling'],
    mapLabel: { lon: 27.48, lat: 43.28 },
  },
  {
    id: 'rose-valley',
    name: 'Rose Valley',
    shortName: 'Rose Valley',
    color: '#b86776',
    pale: '#f1dce0',
    description: 'A sheltered east–west corridor where aromatic varieties meet mountain air and centuries-old rose country.',
    climate: 'Sheltered valley · balanced and aromatic',
    signatures: ['Karlovo Misket', 'Red Misket', 'Muscat'],
    mapLabel: { lon: 24.82, lat: 42.62 },
  },
  {
    id: 'thracian-lowland',
    name: 'Thracian Lowland',
    shortName: 'Thrace',
    color: '#a64f3f',
    pale: '#efd9d2',
    description: 'Bulgaria’s warm southern heartland, best known for generous reds, old cellars and a fast-growing estate scene.',
    climate: 'Warm continental · long, dry growing season',
    signatures: ['Mavrud', 'Rubin', 'Syrah'],
    mapLabel: { lon: 25.15, lat: 42.05 },
  },
  {
    id: 'struma-valley',
    name: 'Struma Valley',
    shortName: 'Struma',
    color: '#72536f',
    pale: '#e8dce7',
    description: 'A dramatic southwestern valley with Mediterranean warmth and Bulgaria’s most place-specific red grapes.',
    climate: 'Mediterranean influence · hot and dry',
    signatures: ['Shiroka Melnishka Loza', 'Melnik 55', 'Ruen'],
    mapLabel: { lon: 23.22, lat: 41.72 },
  },
]

export const wineries: Winery[] = [
  {
    id: 'villa-melnik',
    name: 'Villa Melnik',
    locality: 'Harsovo',
    province: 'Blagoevgrad',
    region: 'struma-valley',
    lat: 41.473205,
    lon: 23.390325,
    summary: 'A family estate above the Melnik sandstone country, with a strong focus on the valley’s indigenous red varieties.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Shiroka Melnishka Loza', 'Melnik 55', 'Ruen'],
    experiences: ['Tastings', 'Cellar tour', 'Events', 'Family-friendly'],
    featured: true,
    website: 'https://villamelnik.com',
  },
  {
    id: 'orbelus',
    name: 'Orbelus',
    locality: 'Kromidovo',
    province: 'Blagoevgrad',
    region: 'struma-valley',
    lat: 41.45,
    lon: 23.39,
    summary: 'An organically farmed estate whose distinctive half-barrel cellar sits among the warm hills near Melnik.',
    styles: ['Red', 'Rosé', 'Orange / low-intervention'],
    grapes: ['Shiroka Melnishka Loza', 'Melnik 55', 'Sandanski Misket'],
    experiences: ['Tastings', 'Cellar tour'],
    organic: true,
    featured: true,
    website: 'https://orbelus.bg',
  },
  {
    id: 'zornitza',
    name: 'Zornitza Family Estate',
    locality: 'Zornitza',
    province: 'Blagoevgrad',
    region: 'struma-valley',
    lat: 41.55,
    lon: 23.43,
    summary: 'A vineyard retreat pairing polished estate wines with a destination restaurant, spa and sweeping Melnik views.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Melnik 55', 'Syrah', 'Chardonnay'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant'],
    featured: true,
    website: 'https://zornitzaestate.com',
  },
  {
    id: 'damianitza',
    name: 'Damianitza',
    locality: 'Damianitsa',
    province: 'Blagoevgrad',
    region: 'struma-valley',
    lat: 41.52,
    lon: 23.27,
    summary: 'A long-established southwest producer associated with expressive Melnik, Rubin and international red blends.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Melnik 55', 'Rubin', 'Cabernet Sauvignon'],
    experiences: ['Tastings', 'Cellar tour'],
  },
  {
    id: 'logodaj',
    name: 'Logodaj Winery',
    locality: 'Logodazh',
    province: 'Blagoevgrad',
    region: 'struma-valley',
    lat: 42.01,
    lon: 22.98,
    summary: 'A western-valley winery championing local red grapes from vineyards close to the North Macedonian border.',
    styles: ['Red', 'Rosé'],
    grapes: ['Shiroka Melnishka Loza', 'Ruen', 'Rubin'],
    experiences: ['Tastings', 'Cellar tour'],
    website: 'https://logodajwinery.com',
  },
  {
    id: 'rupel',
    name: 'Rupel Winery',
    locality: 'Dolno Spanchevo',
    province: 'Blagoevgrad',
    region: 'struma-valley',
    lat: 41.421839,
    lon: 23.378447,
    summary: 'A small contemporary winery in the sunniest reach of the Struma, close to the Rupel Gorge and Greek border.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Melnik 55', 'Sandanski Misket', 'Tamianka'],
    experiences: ['Tastings', 'Cellar tour', 'Events'],
    website: 'https://rupel-wine.com/',
  },
  {
    id: 'medi-valley',
    name: 'Medi Valley',
    locality: 'Smochevo',
    province: 'Kyustendil',
    region: 'struma-valley',
    lat: 42.17,
    lon: 23.08,
    summary: 'A modern estate at the northern gateway to the Struma corridor, surrounded by mountain slopes and orchard country.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Sandanski Misket', 'Melnik 55', 'Merlot'],
    experiences: ['Tastings', 'Cellar tour'],
    website: 'https://medivalley.bg',
  },
  {
    id: 'bessa-valley',
    name: 'Bessa Valley',
    locality: 'Ognianovo',
    province: 'Pazardzhik',
    region: 'thracian-lowland',
    lat: 42.118222,
    lon: 24.41925,
    summary: 'A limestone-rich estate known for structured red blends and expansive vineyard views west of Plovdiv.',
    styles: ['Red', 'Rosé'],
    grapes: ['Merlot', 'Syrah', 'Petit Verdot'],
    experiences: ['Tastings', 'Cellar tour'],
    featured: true,
    website: 'https://bessavalley.com',
  },
  {
    id: 'villa-yustina',
    name: 'Villa Yustina',
    locality: 'Ustina',
    province: 'Plovdiv',
    region: 'thracian-lowland',
    lat: 42.03995,
    lon: 24.51945,
    summary: 'An approachable Rhodope-foothills estate with broad views, visitor facilities and a varied wine portfolio.',
    styles: ['Red', 'White', 'Rosé', 'Sparkling'],
    grapes: ['Mavrud', 'Rubin', 'Sauvignon Blanc'],
    experiences: ['Tastings', 'Cellar tour', 'Restaurant', 'Events', 'Family-friendly'],
    featured: true,
    website: 'https://villayustina.com',
  },
  {
    id: 'dragomir',
    name: 'Dragomir Winery Estate',
    locality: 'Brestnik',
    province: 'Plovdiv',
    region: 'thracian-lowland',
    lat: 42.06,
    lon: 24.77,
    summary: 'A boutique producer just south of Plovdiv, recognised for carefully made Mavrud, Rubin and layered blends.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Mavrud', 'Rubin', 'Dimyat'],
    experiences: ['Tastings', 'Cellar tour'],
    website: 'https://dragomir.bg',
  },
  {
    id: 'zagreus',
    name: 'Zagreus Winery',
    locality: 'Popovitsa',
    province: 'Plovdiv',
    region: 'thracian-lowland',
    lat: 42.110162,
    lon: 25.114489,
    summary: 'A Mavrud specialist in the eastern Plovdiv plain, working with organically farmed estate vineyards.',
    styles: ['Red', 'Rosé', 'Orange / low-intervention'],
    grapes: ['Mavrud', 'Cabernet Sauvignon', 'Syrah'],
    experiences: ['Tastings', 'Cellar tour'],
    organic: true,
    website: 'https://zagreus.org',
  },
  {
    id: 'midalidare',
    name: 'Midalidare Estate',
    locality: 'Mogilovo',
    province: 'Stara Zagora',
    region: 'thracian-lowland',
    lat: 42.341747,
    lon: 25.4059,
    summary: 'A large country estate with two cellars, landscaped grounds and a serious programme of sparkling and still wines.',
    styles: ['Red', 'White', 'Rosé', 'Sparkling'],
    grapes: ['Syrah', 'Cabernet Franc', 'Chardonnay'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant', 'Events', 'Family-friendly'],
    featured: true,
    website: 'https://midalidare.bg',
  },
  {
    id: 'edoardo-miroglio',
    name: 'Edoardo Miroglio',
    locality: 'Elenovo',
    province: 'Sliven',
    region: 'thracian-lowland',
    lat: 42.403876,
    lon: 26.155955,
    summary: 'An Italian-founded estate amid the hills near Nova Zagora, especially noted for traditional-method sparkling wine.',
    styles: ['Red', 'White', 'Rosé', 'Sparkling'],
    grapes: ['Mavrud', 'Pinot Noir', 'Chardonnay'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant'],
    website: 'https://www.emiroglio-wine.com',
  },
  {
    id: 'katarzyna',
    name: 'Katarzyna Estate',
    locality: 'Mezek',
    province: 'Haskovo',
    region: 'thracian-lowland',
    lat: 41.74,
    lon: 26.08,
    summary: 'A borderland estate set among rolling vineyards near Mezek, producing ripe, polished southern Bulgarian wines.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Mavrud', 'Rubin', 'Syrah'],
    experiences: ['Tastings', 'Cellar tour', 'Restaurant'],
    featured: true,
    website: 'https://katarzyna.bg',
  },
  {
    id: 'bratanov',
    name: 'Bratanov Family Winery',
    locality: 'Shishmanovo',
    province: 'Haskovo',
    region: 'thracian-lowland',
    lat: 41.94,
    lon: 25.91,
    summary: 'A small family producer with characterful indigenous-variety bottlings and an experimental cellar spirit.',
    styles: ['Red', 'White', 'Rosé', 'Orange / low-intervention'],
    grapes: ['Rubin', 'Tamianka', 'Mavrud'],
    experiences: ['Tastings', 'Cellar tour'],
    website: 'https://bratanov.wine',
  },
  {
    id: 'castra-rubra',
    name: 'Castra Rubra',
    locality: 'Kolarovo',
    province: 'Haskovo',
    region: 'thracian-lowland',
    lat: 41.93,
    lon: 25.89,
    summary: 'A striking modern cellar in the Sakar foothills, a warm southern zone known for full-flavoured reds.',
    styles: ['Red', 'Rosé'],
    grapes: ['Mavrud', 'Rubin', 'Merlot'],
    experiences: ['Tastings', 'Cellar tour'],
  },
  {
    id: 'chateau-copsa',
    name: 'Chateau Copsa',
    locality: 'Moskovets',
    province: 'Plovdiv',
    region: 'rose-valley',
    lat: 42.64793,
    lon: 24.70577,
    summary: 'A turreted vineyard hotel between the Balkan Mountains and Sredna Gora, close to Karlovo and rose fields.',
    styles: ['Red', 'White', 'Rosé', 'Sparkling'],
    grapes: ['Karlovo Misket', 'Red Misket', 'Chardonnay'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant', 'Events'],
    featured: true,
    website: 'https://chateaucopsa.com',
  },
  {
    id: 'starosel',
    name: 'Starosel Wine & Spa',
    locality: 'Starosel',
    province: 'Plovdiv',
    region: 'rose-valley',
    lat: 42.49,
    lon: 24.55,
    summary: 'A large wine-and-spa complex inspired by Thracian architecture and set near the archaeological sites of Starosel.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Mavrud', 'Muscat', 'Cabernet Sauvignon'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant', 'Events', 'Family-friendly'],
    website: 'https://starosel.com',
  },
  {
    id: 'bononia',
    name: 'Bononia Estate',
    locality: 'Koshava',
    province: 'Vidin',
    region: 'danube-plain',
    lat: 44.003109,
    lon: 23.02353,
    summary: 'A restored riverside estate in Bulgaria’s far northwest, where vineyards look directly toward the Danube.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Gamza', 'Dimyat', 'Cabernet Franc'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant'],
    featured: true,
    website: 'https://bononiaestate.com/en/',
  },
  {
    id: 'magura',
    name: 'Magura Winery',
    locality: 'Rabisha',
    province: 'Vidin',
    region: 'danube-plain',
    lat: 43.71756,
    lon: 22.599708,
    summary: 'A singular northwest cellar whose bottles mature in galleries beside the remarkable Magura Cave.',
    styles: ['Red', 'White', 'Rosé', 'Sparkling'],
    grapes: ['Gamza', 'Vrachanski Misket', 'Riesling'],
    experiences: ['Tastings', 'Cellar tour'],
    featured: true,
    website: 'https://magurawinery.bg',
  },
  {
    id: 'borovitza',
    name: 'Borovitza Winery',
    locality: 'Borovitsa',
    province: 'Vidin',
    region: 'danube-plain',
    lat: 43.586611,
    lon: 22.758433,
    summary: 'A cult-scale cellar among Belogradchik’s red rock formations, making vivid wines from scattered northwest sites.',
    styles: ['Red', 'White', 'Rosé', 'Orange / low-intervention'],
    grapes: ['Gamza', 'Pamid', 'Rkatsiteli'],
    experiences: ['Tastings', 'Cellar tour'],
  },
  {
    id: 'burgozone',
    name: 'Château Burgozone',
    locality: 'Leskovets',
    province: 'Vratsa',
    region: 'danube-plain',
    lat: 43.72152,
    lon: 24.00823,
    summary: 'A Danube-bank estate near Oryahovo with north-facing river slopes and an unusually open horizon.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Gamza', 'Tamianka', 'Cabernet Sauvignon'],
    experiences: ['Tastings', 'Cellar tour', 'Events'],
    website: 'https://www.burgozone.bg/en/',
  },
  {
    id: 'lovico-suhindol',
    name: 'Lovico Suhindol',
    locality: 'Suhindol',
    province: 'Veliko Tarnovo',
    region: 'danube-plain',
    lat: 43.19,
    lon: 25.18,
    summary: 'A historic cooperative-scale name from one of north-central Bulgaria’s best-known wine towns.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Gamza', 'Vrachanski Misket', 'Merlot'],
    experiences: ['Tastings', 'Cellar tour'],
  },
  {
    id: 'yalovo',
    name: 'Yalovo Winery',
    locality: 'Yalovo',
    province: 'Veliko Tarnovo',
    region: 'danube-plain',
    lat: 42.91,
    lon: 25.65,
    summary: 'A small, low-intervention-minded cellar south of Veliko Tarnovo reviving overlooked local vineyard material.',
    styles: ['Red', 'White', 'Rosé', 'Orange / low-intervention'],
    grapes: ['Dimyat', 'Pamid', 'Rubin'],
    experiences: ['Tastings', 'Cellar tour'],
  },
  {
    id: 'maryan',
    name: 'Maryan Winery',
    locality: 'Maryan',
    province: 'Veliko Tarnovo',
    region: 'danube-plain',
    lat: 42.92,
    lon: 25.87,
    summary: 'A family-run boutique winery in the Elena Balkan, pairing local character with a quiet rural setting.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Dimyat', 'Rubin', 'Chardonnay'],
    experiences: ['Tastings', 'Cellar tour', 'Family-friendly'],
    website: 'https://maryanwinery.com',
  },
  {
    id: 'seven-generations',
    name: 'Seven Generations',
    locality: 'Mechka',
    province: 'Ruse',
    region: 'danube-plain',
    lat: 43.710578,
    lon: 25.81527,
    summary: 'A vineyard hotel above the Danube near Ruse, designed for slow lunches, tastings and a night among the vines.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Cabernet Sauvignon', 'Merlot', 'Muscat'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant', 'Family-friendly'],
  },
  {
    id: 'salla-estate',
    name: 'Salla Estate',
    locality: 'Blaskovo',
    province: 'Varna',
    region: 'black-sea',
    lat: 43.118755,
    lon: 27.330755,
    summary: 'A compact estate in the rolling Provadia countryside, with equestrian grounds and aromatic northern whites.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Vrachanski Misket', 'Riesling', 'Pinot Noir'],
    experiences: ['Tastings', 'Cellar tour', 'Stay', 'Restaurant', 'Family-friendly'],
    featured: true,
    website: 'https://salla.bg',
  },
  {
    id: 'tsarev-brod',
    name: 'Tsarev Brod',
    locality: 'Tsarev Brod',
    province: 'Shumen',
    region: 'black-sea',
    lat: 43.348917,
    lon: 27.012333,
    summary: 'A thoughtful northeast producer known for expressive whites and the revival of the rare Gergana grape.',
    styles: ['Red', 'White', 'Rosé', 'Orange / low-intervention'],
    grapes: ['Gergana', 'Dimyat', 'Traminer'],
    experiences: ['Tastings', 'Cellar tour'],
    featured: true,
    website: 'https://tsarevbrod.com',
  },
  {
    id: 'varna-winery',
    name: 'Varna Winery',
    locality: 'General Kantardzhievo',
    province: 'Varna',
    region: 'black-sea',
    lat: 43.359722,
    lon: 27.981667,
    summary: 'A coastal-hills winery north of Varna with fresh white, rosé and sparkling styles shaped by nearby sea air.',
    styles: ['Red', 'White', 'Rosé', 'Sparkling'],
    grapes: ['Dimyat', 'Sauvignon Blanc', 'Pinot Noir'],
    experiences: ['Tastings', 'Cellar tour', 'Events'],
  },
  {
    id: 'euxinograd',
    name: 'Euxinograd Cellar',
    locality: 'Sts. Constantine and Helena',
    province: 'Varna',
    region: 'black-sea',
    lat: 43.22,
    lon: 27.99,
    summary: 'A historic royal-estate cellar on the coast, surrounded by formal gardens just north of Varna.',
    styles: ['White', 'Rosé', 'Dessert'],
    grapes: ['Dimyat', 'Riesling', 'Chardonnay'],
    experiences: ['Tastings', 'Cellar tour'],
  },
  {
    id: 'minkov-brothers',
    name: 'Minkov Brothers',
    locality: 'Venets',
    province: 'Burgas',
    region: 'rose-valley',
    lat: 42.639722,
    lon: 26.803056,
    summary: 'A sizeable estate near the Sungurlare Valley combining an established cellar tradition with modern visitor spaces.',
    styles: ['Red', 'White', 'Rosé'],
    grapes: ['Dimyat', 'Muscat', 'Cabernet Sauvignon'],
    experiences: ['Tastings', 'Cellar tour', 'Events'],
    website: 'https://minkovbrothers.bg',
  },
]

export const wineStyles: WineStyle[] = ['Red', 'White', 'Rosé', 'Sparkling', 'Orange / low-intervention', 'Dessert']

export const experienceOptions: Experience[] = ['Tastings', 'Cellar tour', 'Stay', 'Restaurant', 'Events', 'Family-friendly']

export const regionById = Object.fromEntries(regions.map((region) => [region.id, region])) as Record<RegionId, Region>
